# 基础——defer、panic、recover及异常处理机制 #

虽然Goroutine能够实现高并发，但是如果某个Goroutine panic了，而且这个Goroutine里面没有捕获recover，那么整个进程就会挂掉。所以，好的习惯是每当go产生一个goroutine，就需要写下recover。

## 1. defer ##

* defer语句将在函数最终返回前被执行（由编译器在return前展开defer语句中的函数来实现）。一个函数中可以调用多次defer语句，按照先进后出的原则。即使panic也会执行defer

语句定义的延迟函数，会在当前上层函数返回前调用。延迟的函数调用被压入一个栈中。当函数返回时， 会按照后进先出的顺序调用被延迟的函数调用。**需要注意的是，延迟调用函数的参数会立刻生成，但是其在上层函数返回前都不会被调用。**

* os.Exit退出时不会调用defer指定的函数
* os.Exit退出时不输出当前调用栈信息

函数中存在defer语句时的执行顺序是：先return后执行defer语句，最后才结束函数调用。

```
package main

import "fmt"

func test() (i int, err error) {
    s := "init..."
    defer func(s string) {
        fmt.Println("defer:" + s)
    }(s)
    s = "changed..."
    return fmt.Println("return")
}

func main() {
    test()
    //输出：
    //return
    //defer:init...
}
```

## 2. panic ##

* 调用panic时，正常的函数执行流程立即终止（但是函数中之前使用defer延迟执行的语句仍正常执行），并导致逐层向上执行panic流程，直到该所属的进程中所有正在执行的函数被终止（除非使用了recover捕捉）。

## 3. recover ##

* recover用于终止panic错误流程。一般情况下，recover放在defer中定义执行。

注意：当心，recover成为恶魔

* 容易形成僵尸进程，导致healthcheck失效
* let it crash往往是恢复不确定性错误的最好方法

## 4. 异常处理机制 ##

* Go没有异常机制，遵循及早失败，避免嵌套的原则。
* error类型实现了error接口，可以通过errors.New来快速创建错误实例。

```
type error interface{
    Error() string
}
```

```
errors.New("there is an error.")
```

定义不同的错误变量，以便于判定错误类型。

```
var LessThanError error = errors.New("number can not be less than the target")
var GreaterThanError error = errors.New("number can not be greater than the target")

result,err:=f()
if err==LessThanError{
    ...
}
if err==GreaterThanError{
    ...
}
```
